CREATE DATABASE IF NOT EXISTS brain_glitch CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE brain_glitch;

CREATE TABLE IF NOT EXISTS leaderboard (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(30) NOT NULL,
  score INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_score ON leaderboard(score);
